[build]
rustflags = ["-Ctarget-cpu=sapphirerapids"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Ctarget-cpu=native", "-C", "link-arg=--ld-path=/usr/bin/mold"]

[unstable]
build-std = ["std", "core", "alloc"]
