// autogenerated metadata - do not edit!
#[derive(Debug)]
pub struct LibVersion {
    pub name: &'static str,
    pub version: &'static str,
}

impl LibVersion {
    pub fn get_name(&self) -> &'static str {
        self.name
    }
    pub fn get_version(&self) -> &'static str {
        self.version
    }
}

pub struct LibVersionMap {
    pub list: &'static [LibVersion],
}

impl LibVersionMap {
    pub fn get(&self, name: &str) -> Option<&LibVersion> {
        self.list.iter().find(|v| v.get_name() == name)
    }
}

/// AUTO-GENERATED BY build.rs
pub const PROJECT_NAME: &str = "rust-be-template";
pub const PROJECT_VERSION: &str = "0.1.0";
pub const BUILD_TIME_UTC: &str = "2025-08-08T19:46:50.462962100+00:00";
pub const RUSTC_VERSION: &str = "rustc 1.89.0 (29483883e 2025-08-04)";
pub const LIB_VERSIONS: [LibVersion; 41] = [
    LibVersion { name: "anyhow", version: "1.0.98" },
    LibVersion { name: "argon2", version: "0.5.3" },
    LibVersion { name: "aws-sdk-s3", version: "1.101.0" },
    LibVersion { name: "axum", version: "0.8.4" },
    LibVersion { name: "axum-extra", version: "0.10.1" },
    LibVersion { name: "axum-server", version: "0.7.2" },
    LibVersion { name: "bigdecimal", version: "0.4.8" },
    LibVersion { name: "bitcode", version: "0.6.6" },
    LibVersion { name: "chrono", version: "0.4.41" },
    LibVersion { name: "chrono-tz", version: "0.10.4" },
    LibVersion { name: "comrak", version: "0.40.0" },
    LibVersion { name: "diesel", version: "2.2.12" },
    LibVersion { name: "diesel-async", version: "0.6.1" },
    LibVersion { name: "dotenvy", version: "0.15.7" },
    LibVersion { name: "email_address", version: "0.2.9" },
    LibVersion { name: "image", version: "0.25.6" },
    LibVersion { name: "internment", version: "0.8.6" },
    LibVersion { name: "ipnet", version: "2.11.0" },
    LibVersion { name: "lettre", version: "0.11.18" },
    LibVersion { name: "mimalloc", version: "0.1.47" },
    LibVersion { name: "mime_guess", version: "2.0.5" },
    LibVersion { name: "num_cpus", version: "1.17.0" },
    LibVersion { name: "rand", version: "0.8.5" },
    LibVersion { name: "rand", version: "0.9.2" },
    LibVersion { name: "reqwest", version: "0.12.22" },
    LibVersion { name: "rust-embed", version: "8.7.2" },
    LibVersion { name: "rustls", version: "0.21.12" },
    LibVersion { name: "rustls", version: "0.23.31" },
    LibVersion { name: "scc", version: "2.3.4" },
    LibVersion { name: "serde", version: "1.0.219" },
    LibVersion { name: "serde_derive", version: "1.0.219" },
    LibVersion { name: "serde_json", version: "1.0.142" },
    LibVersion { name: "sysinfo", version: "0.36.1" },
    LibVersion { name: "tokio", version: "1.47.1" },
    LibVersion { name: "tower-http", version: "0.6.6" },
    LibVersion { name: "tracing", version: "0.1.41" },
    LibVersion { name: "tracing-appender", version: "0.2.3" },
    LibVersion { name: "tracing-subscriber", version: "0.3.19" },
    LibVersion { name: "uuid", version: "1.17.0" },
    LibVersion { name: "zeroize", version: "1.8.1" },
    LibVersion { name: "zstd", version: "0.13.3" },
];
pub const LIB_VERSION_MAP: LibVersionMap = LibVersionMap { list: &LIB_VERSIONS };
